[project]
name = "yt-dlp-mohan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "trogon>=0.6.0",
    "typer>=0.15.3",
]
